services:
  - type: web
    name: app-login-premier-xdangel
    env: docker
    plan: free
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:OjnTlHETWrnFAi3+xVb6eBwTDp5sYWho4RVCiJJPdXk=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: app-login-db-xdangel
          property: host
      - key: DB_PORT
        fromDatabase:
          name: app-login-db-xdangel
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: app-login-db-xdangel
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: app-login-db-xdangel
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: app-login-db-xdangel
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        value: xdangel755@gmail.com
      - key: MAIL_PASSWORD
        value: "hfwk xdjv ddbm hyel"
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: xdangel755@gmail.com
      - key: MAIL_FROM_NAME
        value: "Premier Academy"
      - key: APP_OWNER_EMAIL
        value: angel1120171@hotmail.com


databases:
  - name: app-login-db-xdangel
    plan: free
